SwitchNet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #url(r'^$', index.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user_mgr.urls', namespace='user')),
    url(r'^newsfeed/', include('newsfeed.urls', namespace='newsfeed')),
    url(r'^messaging/', include('messaging.urls', namespace='messaging')),
]

messaging/urls.py
from django.conf.urls import url

from . import views

app_name = 'messaging'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

newsfeed/urls.py
from django.conf.urls import url
from . import views

app_name = 'newsfeed'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

user_mgr/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_mgr'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create_account, name = 'register'),
    url(r'^login/$', views.log_in, name ='login'),
]

messaging/models.py
from django.db import models

# Create your models here.

newsfeed/models.py
from django.db import models

# Create your models here.

user_mgr/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from user_mgr.model_field_choices import USER_STATUS, USER_GENDER


class FriendList(models.Model):
    owner   = models.OneToOneField('UserAccount')
    friends = models.ForeignKey(User)

    class Meta():
        verbose_name_plural  = 'FriendList'

class Address(models.Model):
    owner = models.ForeignKey('UserAccount')
    house_address = models.TextField()
    lga = models.CharField(max_length = 25)
    state = models.CharField(max_length = 25)
    country = models.CharField(max_length = 25)

    def __str__(self):
        return self.house_address

    class Meta():
        verbose_name_plural  = 'Address'

class UserAccount(models.Model):
    user = models.OneToOneField(User)
    phone_number = models.CharField(max_length = 15, null = True, blank = True)
    gender = models.CharField(max_length = 10, choices = USER_GENDER, null = True, blank = True)
    status = models.CharField(max_length = 10, choices = USER_STATUS, null = True, blank = True)

    def __str__(self):
        return self.user.username

    class Meta():
        verbose_name_plural  = 'UserAccount'

user_mgr/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserAccount, FriendList, Address

class RegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length = 120, help_text = '150 characters or fewer. Letters, digits and @/./+/-/_ only.', widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Username', 'required': 'required'}))
    first_name = forms.CharField(max_length = 120, help_text = '', widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'First Name', 'required': 'required'}))
    last_name = forms.CharField(max_length = 120, help_text = '',  widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Surname', 'required': 'required'}))
    email = forms.EmailField(max_length = 120,  help_text = '',  widget = forms.EmailInput(attrs = {'class': 'form-control', 'placeholder': 'email@example.com', 'required': 'required'}))
    password = forms.CharField(max_length = 15, help_text = '',  widget = forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': 'password', 'required': 'required'}))

    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email', 'password',)

class LoginForm(forms.ModelForm):
    email = forms.EmailField(max_length = 120,  help_text = '',  widget = forms.EmailInput(attrs = {'class': 'form-control', 'placeholder': 'email@example.com', 'required': 'required'}))
    password = forms.CharField(max_length = 15, help_text = '',  widget = forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': 'password', 'required': 'required'}))
    
    class Meta:
        model = User
        fields = ('email', 'password',)

class UserAccountForm(forms.ModelForm):
    phone_number = forms.CharField(max_length = 120, help_text = '', widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'First Name', 'required': 'required'}))
    
    class Meta:
        model = UserAccount
        fields = ('phone_number', 'gender', 'status')

messaging/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    pass
    return HttpResponse('welcome to messaging')

newsfeed/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    pass
    return HttpResponse('welcome to newsfeed')

user_mgr/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user_mgr.forms import RegistrationForm, LoginForm, UserAccountForm
from user_mgr.models import UserAccount
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth import login, authenticate, logout

# Create your views here.
def index(request):
    #return HttpResponse('welcome to user_mgr')
    context = {
        
    }
    return render(request, 'user_mgr/index.html', context)

def create_account(request):
    reg_form = RegistrationForm()
    context = {
        'reg_form': reg_form
    }
    if request.method == 'POST':
        user = None
        user_reg_form = RegistrationForm(data = request.POST)
        rp = request.POST
        if User.objects.filter(email = rp['email']).exists():
            context['reg_form'] = user_reg_form
            messages.info(request, 'Sorry this email has been taken')
            return redirect(reverse('user_mgr:register'))
        else:
            if user_reg_form.is_valid():
                #user_reg_form.save()
                user = User.objects.create(username = rp['username'], first_name = rp['first_name'], last_name = rp['last_name'], email = rp['email'], )
                user.set_password(rp['password'])
                user.save()
                #create a useraccount for the new customer
                useraccount = UserAccount.objects.create(user = user)
                #messages.success(request, 'Your details have been saved')
                if user:
                   messages.success(request, 'Your details have been saved')
                else:
                    messages.warning(request, 'something went wrong acount not created!! please try again!')
            else: 
                #since django uses uersername and we checked for email only is_valid is False when we enter
                #username a username that alraedy exists so to tackle that we use the else and do this.
                #messages.warning(request, 'Username already exists!!')
                context['reg_form'] = RegistrationForm(data = request.POST)
    return render(request, 'user_mgr/login.html', context)

def log_in(request):
    login_form = LoginForm()
    context = { 'login_form' : login_form }
    if request.method == 'POST':
        rp = request.POST
        login_form = LoginForm(data = request.POST)
        #check if user exists
        if User.objects.filter(email = rp['email']).exists():
            username = User.objects.get(email = rp['email']).username
            auth_user = authenticate(username= username, password = rp['password'])
            if auth_user:
                login(request, auth_user)
                return HttpResponse('<h1>You have been logged in!!<\h1>')
            else: 
                context['login_form'] = login_form
                messages.error(request, 'Sorry your email or password is incorrect!!')
        else: 
            context['login_form'] = login_form
            messages.error(request, 'Sorry this email adddress doest not exist!!')
            
    context['login_form'] = login_form
    return render(request, 'user_mgr/login.html', context)

user_mgr/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>SwitchNet | {% block title %}{% endblock title %}</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="{% static 'SwitchNet/style.css' %}" rel="stylesheet" type="text/css" />
    {% block links %}{% endblock links%}
</head>
<body id="home">
<!-- START PAGE SOURCE -->
<div id="header">
  <div id="innerheader"> <a href="#"><img src="{% static 'SwitchNet/images/logo.png' %}" alt="" class="logo" /></a>
    <div id="mainsearch">
      <form method="get" action="#">
        <input value="search for a domain name..." onclick="this.value=''" name="domain" type="text" class="searchbox" />
        <input type="image" src="{% static 'SwitchNet/images/btn_mainsearch.png' %}" class="btnsearch" />
      </form>
    </div>
  </div>
</div>
<div id="nav">
  <ul id="navigation">
    <li class="navhome"><a href="{% url 'user_mgr:index' %}">Home</a></li>
    <li class="navdomains"><a href="content.html">Domain Names</a></li>
    <li class="navhosting"><a href="hosting.html">Web Hosting</a></li>
    <li class="navabout"><a href="#">About Us</a></li>
    <li class="navorder"><a href="#">Order Now</a></li>
    <li class="right"><img src="{% static 'SwitchNet/images/icon_nav_login.png' %}" alt="" /><a href="#">Control Panel</a></li>
    <li class="right"><img src="{% static 'SwitchNet/images/icon_support.png' %}" alt="" /><a href="{% url 'user_mgr:register' %}">Create Account</a></li>
    <li class="right"><img src="{% static 'SwitchNet/images/icon_support.png' %}" alt="" /><a href="{% url 'user_mgr:login' %}">Login</a></li>
  </ul>
</div>
<div id="content">
    {% block inner_content %}
    
    {% endblock inner_content %}
</div>
<div id="footer">
  <p class="lf">Copyright &copy; 2011 <a href="#">Blue Hosting</a> - All Rights Reserved</p>
  <p class="rf">Design by <a href="http://www.heartinternet.co.uk/">Reseller Hosting</a></p>
  <div style="clear:both;"></div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>

user_mgr/templates/user_mgr/content.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Blue Hosting | Content</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="style.css" rel="stylesheet" type="text/css" />
</head>
<body id="home">
<!-- START PAGE SOURCE -->
<div id="header">
  <div id="innerheader"> <a href="#"><img src="images/logo.png" alt="" class="logo" /></a>
    <div id="mainsearch">
      <form method="get" action="#">
        <input value="search for a domain name..." onclick="this.value=''" name="domain" type="text" class="searchbox" />
        <input type="image" src="images/btn_mainsearch.png" class="btnsearch" />
      </form>
    </div>
  </div>
</div>
<div id="nav">
  <ul id="navigation">
    <li class="navhome"><a href="index.html">Home</a></li>
    <li class="navdomains"><a href="content.html">Domain Names</a></li>
    <li class="navhosting"><a href="hosting.html">Web Hosting</a></li>
    <li class="navabout"><a href="#">About Us</a></li>
    <li class="navorder"><a href="#">Order Now</a></li>
    <li class="right"><img src="images/icon_nav_login.png" alt="" /><a href="#">Control Panel</a></li>
    <li class="right"><img src="images/icon_nav_email.png" alt="" /><a href="#">Email Us</a></li>
    <li class="right"><img src="images/icon_nav_phone.png" alt="" /><span class="hl">(+44)</span> 01234 567 891</li>
  </ul>
</div>
<div id="content">
  <h1>Add your title</h1>
  <p><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut</strong></p>
  <p>Laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
  <div style="clear: both;"></div>
</div>
<div id="footer">
  <p class="lf">Copyright &copy; 2011 <a href="#">Blue Hosting</a> - All Rights Reserved</p>
  <p class="rf">Design by <a href="http://www.heartinternet.co.uk/">Reseller Hosting</a></p>
  <div style="clear:both;"></div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>

user_mgr/templates/user_mgr/hosting.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Blue Hosting | Hosting</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="style.css" rel="stylesheet" type="text/css" />
</head>
<body id="home">
<!-- START PAGE SOURCE -->
<div id="header">
  <div id="innerheader"> <a href="#"><img src="images/logo.png" alt="" class="logo" /></a>
    <div id="mainsearch">
      <form method="get" action="#">
        <input value="search for a domain name..." onclick="this.value=''" name="domain" type="text" class="searchbox" />
        <input type="image" src="images/btn_mainsearch.png" class="btnsearch" />
      </form>
    </div>
  </div>
</div>
<div id="nav">
  <ul id="navigation">
    <li class="navhome"><a href="index.html">Home</a></li>
    <li class="navdomains"><a href="content.html">Domain Names</a></li>
    <li class="navhosting"><a href="hosting.html">Web Hosting</a></li>
    <li class="navabout"><a href="#">About Us</a></li>
    <li class="navorder"><a href="#">Order Now</a></li>
    <li class="right"><img src="images/icon_nav_login.png" alt="" /><a href="#">Control Panel</a></li>
    <li class="right"><img src="images/icon_nav_email.png" alt="" /><a href="#">Email Us</a></li>
    <li class="right"><img src="images/icon_nav_phone.png" alt="" /><span class="hl">(+44)</span> 01234 567 891</li>
  </ul>
</div>
<div id="content">
  <h1>Web Hosting</h1>
  <ul id="promobox">
    <li>
      <h3>Starter</h3>
      <div class="pricebox">
        <p>From Only</p>
        <p class="lrg">&pound;4.99</p>
      </div>
      <ul>
        <li>2,000 MB Diskspace</li>
        <li>20GB Bandwidth</li>
        <li>1,000 Mail Boxes</li>
        <li>10 MySQL Databases</li>
        <li>Website Builder Plus</li>
        <li>Free &amp; Fast Support</li>
        <li>Powerful Control Panel</li>
        <li>30-Day Money Back Guarantee</li>
      </ul>
      <p><a href="#">Order Now</a></p>
    </li>
    <li class="two">
      <h3>Business</h3>
      <div class="pricebox">
        <p>From Only</p>
        <p class="lrg">&pound;8.99</p>
      </div>
      <ul>
        <li>4000 MB Web Space </li>
        <li>40GB Bandwidth </li>
        <li>2000 Mail Boxes </li>
        <li>20 MySQL Databases </li>
        <li>Website Builder Plus </li>
        <li>Free and Fast Support </li>
        <li>Powerful Control Panel </li>
        <li>30-Day Money-Back Guarantee</li>
      </ul>
      <p><a href="#">Order Now</a></p>
    </li>
    <li class="three">
      <h3>Professional</h3>
      <div class="pricebox">
        <p>From Only</p>
        <p class="lrg">&pound;9.99</p>
      </div>
      <ul>
        <li>6000 MB Web Space </li>
        <li>60GB Bandwidth </li>
        <li>2000 Mail Boxes </li>
        <li>30 MySQL Databases </li>
        <li>Website Builder Plus </li>
        <li>Free and Fast Support </li>
        <li>Powerful Control Panel </li>
        <li>30-Day Money-Back Guarantee</li>
      </ul>
      <p><a href="#">Order Now</a></p>
    </li>
  </ul>
  <div style="clear: both;"></div>
</div>
<div id="footer">
  <p class="lf">Copyright &copy; 2011 <a href="#">Blue Hosting</a> - All Rights Reserved</p>
  <p class="rf">Design by <a href="http://www.heartinternet.co.uk/">Reseller Hosting</a></p>
  <div style="clear:both;"></div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>

user_mgr/templates/user_mgr/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Welcome{% endblock title %}

{% block inner_content %}


  <div id="intro" class="box">
    <div id="introleft">
      <h1><span class="hlalt">AFFORDABLE</span><br />
        WEB HOSTING</h1>
      <p>STARTING FROM ONLY: &pound;1.99</p>
      <ul class="btns">
        <li><a href="#">ORDER NOW</a></li>
        <li class="alt"><a href="#">FIND OUT MORE</a></li>
      </ul>
    </div>
    <ul id="introlist">
      <li class="listheading">Web hosting packages include the following:</li>
      <li><img src="{% static 'SwitchNet/images/icon_webspace.png' %}" alt="" />5Gb of Web Space</li>
      <li><img src="{% static 'SwitchNet/images/icon_wb.png' %}" alt="" />Free Website Builder</li>
      <li><img src="{% static 'SwitchNet/images/icon_datatransfer.png' %}" alt="" />Unlimited Data Transfer</li>
      <li><img src="{% static 'SwitchNet/images/icon_email.png' %}" alt="" />1,000 1Gb Email Accounts</li>
      <li><img src="{% static 'SwitchNet/images/icon_db.png' %}" alt="" />10 MySQL Databases</li>
      <li><img src="{% static 'SwitchNet/images/icon_cp.png' %}" alt="" />Powerful Control Panel</li>
      <li><img src="{% static 'SwitchNet/images/icon_support.png' %}" alt="" />24x7x365 Support</li>
      <li><img src="{% static 'SwitchNet/images/icon_instant.png' %}" alt="" />Instant Account Activation</li>
      <li><img src="{% static 'SwitchNet/images/icon_virus.png' %}" alt="" />Virus Scanning</li>
      <li><img src="{% static 'SwitchNet/images/icon_ruby.png' %}" alt="" />PHP5 - Ruby/Rails - Perl</li>
      <li><img src="{% static 'SwitchNet/images/icon_cancel.png' %}" alt="" />Cancel Anytime</li>
      <li><img src="{% static 'SwitchNet/images/icon_moneyback.png' %}" alt="" />Money Back Guarantee</li>
    </ul>
  </div>
  <div id="fpdomains" class="box">
    <h3>Domain Names</h3>
    <p>Lorem ipsum dolor sit amet, consectetuer.</p>
    <ul>
      <li>
        <p class="left">.co.uk</p>
        <p class="right">&pound;2.99</p>
      </li>
      <li>
        <p class="left">.com</p>
        <p class="right">&pound;8.99</p>
      </li>
      <li>
        <p class="left">.eu</p>
        <p class="right">&pound;8.99</p>
      </li>
    </ul>
    <p class="desc">Lorem ipsum dolor sit amet, consectetuer.</p>
    <div id="fpsearch">
      <form method="get" action="#">
        <input type="text" class="fpsearchbox" value="www." onclick="this.value=''" name="domain" />
        <input type="image" src="{% static 'SwitchNet/images/btn_fpsearch.png' %}" class="fpbtnsearch" />
      </form>
    </div>
  </div>
  <div id="wbp" class="box">
    <div id="wbpright">
      <div class="pricebox">
        <p>ONLY</p>
        <p class="big">&pound;29.99 </p>
        <p>PER YEAR</p>
      </div>
      <ul class="btns">
        <li><a href="#">ORDER NOW&nbsp; </a></li>
      </ul>
    </div>
    <img src="{% static 'SwitchNet/images/fp_wbp.jpg' %}" alt="" />
    <h3>Website Builder Plus</h3>
    <p><strong>Get a professional looking website in minutes</strong></p>
    <ul id="wbplist">
      <li>UNLIMITED pages</li>
      <li>Forums, galleries &amp; blogs</li>
      <li>UNLIMITED updates</li>
      <li>E-commerce shops</li>
      <li>Over 500 templates</li>
      <li>Instant online setup</li>
    </ul>
  </div>
  <div id="wwh" class="box">
    <h3>Windows Web Hosting</h3>
    <p>Lorem ipsum dolor sit amet, consectetuer Lorem ipsum.<br />
      <strong>Prices start from as little as &pound;5.99 per month</strong></p>
    <ul class="btns">
      <li><a href="#">VIEW PLANS</a></li>
      <li class="alt"><a href="#">FIND OUT MORE</a></li>
    </ul>
  </div>
  <div id="newsbox" class="box">
    <h3>Hosting News</h3>
    <p>Catch the latest web hosting industry news here...</p>
    <ul>
      <li>
        <p class="date"> <span class="day">05</span><br />
          <span class="month">NOV</span> </p>
        <h4><a href="#">News Title Here</a></h4>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam</p>
      </li>
      <li>
        <p class="date"> <span class="day">03</span><br />
          <span class="month">NOV</span> </p>
        <h4><a href="#">News Title Here</a></h4>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam</p>
      </li>
    </ul>
  </div>
  <div id="scripts" class="box">
    <h3>1-Click Installs</h3>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed</p>
    <img src="{% static 'SwitchNet/images/fp_scripts.png' %}" alt="" />
    <p><strong>With select hosting packages.</strong></p>
    <ul class="btns">
      <li><a href="#">VIEW PLANS</a></li>
    </ul>
  </div>
  <div id="reviews" class="box">
    <h3>Customer Testimonials</h3>
    <p>We have many happy customers</p>
    <ul>
      <li>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nie...<br />
          <span class="hl"><strong>Mr Roberts, Birmingham</strong></span></p>
      </li>
      <li class="none">
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nie...<br />
          <span class="hl"><strong>Mrs Robinson, Leeds</strong></span></p>
      </li>
    </ul>
  </div>
  <div style="clear:both;"></div>


{% endblock inner_content %}

user_mgr/templates/user_mgr/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block links %}<link href="{% static 'SwitchNet/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />{% endblock links%}
{% block title %}Create Account{% endblock title %}

{% block inner_content %}
    <a href = "{% url 'user_mgr:index' %}"><h1>Home</h1></a>
    <h2>Get shit done</h2>
    <hr>
    {% if messages %}
        {% for msg in messages %}
            <p>{{msg}}</p>
        {% endfor %}
    {% endif %}

    <div>
        <a href="{% url 'user_mgr:register' %}"><b>Register Here</b></a>
    </div>
    <br>
    <div>
        <a href="{% url 'user_mgr:login' %}"><b>Log in Here</b></a> 
    </div>
    <br>

    {% if reg_form %}
        <form method="post" action="">
            {% csrf_token %}
            {{ reg_form.as_p }}
        <input type = "submit", value="Submit" class="btn">
        </form>
        {% elif login_form %}
        <form method="post" action="">
            {% csrf_token %}
            {{ login_form.as_p }}
            <input type = "submit", value="Submit" class="btn">
        </form>
    {% endif %} 
  {% endblock inner_content %}

user_mgr/templates/user_mgr/zxc.html
{% load static %}
<!Doctype html>
<html>
    <head>
        <link rel = "stylesheet" href = "{% static 'user_mgr/css/bootstrap.min.css' %}">
		<link rel = "stylesheet" href = "{% static 'user_mgr/css/bootstrap.css' %}">
		<link rel = "stylesheet" href = "{% static 'user_mgr/css/font-awesome.min.css' %}">
		<link rel = "stylesheet" href = "{% static 'user_mgr/css/font-awesome.css' %}">
        
        <title>Welcome user</title>
        <meta charset = "utf-8">
    </head>
    <body>
        <div class = "container">
<!--            <div class = "wwrapper">-->
                <a href = "{% url 'user_mgr:index' %}"><h1>Home</h1></a>
                <h2>Get shit done</h2>
                <hr>
            {% if messages %}
                {% for msg in messages %}
                    <p>{{msg}}</p>
                {% endfor %}
            {% endif %}
                <div>
                    <a href="{% url 'user_mgr:register' %}"><b>Register Here</b></a>
                </div>
                <br>
                <div>
                    <a href="{% url 'user_mgr:login' %}"><b>Log in Here</b></a> 
                </div>
                <br>

                {% if reg_form %}
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ reg_form.as_p }}
                        <input type = "submit", value="Submit" class="btn">
                    </form>
                {% elif login_form %}
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ login_form.as_p }}
                        <input type = "submit", value="Submit" class="btn">
                    </form>
                {% endif %} 
<!--            </div>-->
        </div>
    </body>   
</html>

user_mgr/templates/user_mgr/zxc1.html
<!Doctype html>
<html>
    <head>
        <title>Register user</title>
        <meta charset = "utf-8">
    </head>
    <body>
        <h1>Register</h1>
        <h2>Start getting shit done</h2>
        <hr>
        <div>
            <form method="post" action="">
                {{ reg_form.as_p }}
                <input type = "submit", value="Submit">
            </form>
        </div>
    </body>   
</html>

user_mgr/templates/user_mgr/zxc2.html
<!Doctype html>
<html>
    <head>
        <title>Log In</title>
        <meta charset = "utf-8">
    </head>
    <body>
        <h1>Log In</h1>
        <h2>Continue getting shit done</h2>
        <hr>
        <div>
           
        </div>
    </body>   
</html>